version: "3.2"

services:
    mongodb:
        image: mongo:4.2.2-bionic
        container_name: mongodb
        restart: unless-stopped
        ports:
            - 27017-27019:27017-27019
        volumes:
            - SAPDevelop/personal/myFinance/data:/data/db
volumes:
  SAPDevelop/personal/myFinance/data:
